name: rl
channels:
  - nvidia
  - rapidsai
  - numba
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.*
  - jupyterlab=2.2.*
  - shapely=1.6.*
  - pyshp=2.1.*
  - pandas=1.1.*
  - pytorch=1.7.*
  - pytorch-lightning=1.1.*
  - tensorboardx=2.1.*
  - matplotlib=3.3.*
  - gym=0.18.*
  - shap=0.37.*
  - wandb=0.10.*
  - click=7.1.*
  - cugraph=0.16.*
  - cudatoolkit=10.2.*
  - pip
  - pip:
      - torchvision
      - opencv-python
      - ray[rllib]